import { Providers } from './Providers';

import './globals.css';

export const metadata = {
  title: 'Roof Resource',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
